FROM node:20-alpine

WORKDIR /app

# Copy the shared package file from the root directory
COPY package*.json ./

RUN npm install

# Copy all directories (backend, frontend, etc.) into the container
COPY . .

EXPOSE 5000

CMD ["npm", "run", "start:backend"]